Repository WildCodeSchool/2023-09-PHP-LYON-meet-n-zik, pull requests merged in 2023-11, with the labels that each got.

#2 S01 us02 navbar creation
  src/View/layout.html.twig
Labels: Changes done

#3 S01 us08 creation of the registration page
  public/assets/css/style.css
  public/assets/images/scene-on-fire.png
  public/assets/images/scene-paysage.png
  src/View/Home/login.html.twig
  src/View/Home/signup.html.twig
  src/View/layout.html.twig
Labels: Changes requested

#5 S01 us08 creation of form menu
  public/assets/css/style.css
  public/assets/script.js
  src/View/Home/login.html.twig
  src/View/Home/signup.html.twig
  src/View/layout.html.twig
Labels: Changes done, Needs pair review

#14 S02 us19 create profil page and modification profil page
  public/assets/css/style.css
  src/Controller/UserController.php
  src/Model/UserManager.php
  src/Service/FormVerificationService.php
  src/View/User/edit-user-profil.html.twig
  src/View/User/navbar.html.twig
  src/View/User/user-profil.html.twig
  src/routes.php
Labels: Changes done

#13 S02 us09 ajouter une page apercu profiles
  database.sql
  src/Controller/UserController.php
  src/Model/AbstractManager.php
  src/Model/UserManager.php
  src/View/User/meet.html.twig
  src/View/signup.html.twig
  src/routes.php
Labels: Changes done
